
export const SET_SUGGESTIONS_LIST = 'SET_SUGGESTIONS_LIST'

export const SET_COORDINATE = 'SET_COORDINATE'

export const SAVE_EXACT_ADDRESS = 'SAVE_EXACT_ADDRESS'

export const CLEAR_SUGGESTIONS_LIST = 'CLEAR_SUGGESTIONS_LIST'

export const SET_INEXACT_CITY = 'SET_INEXACT_CITY'

export const SET_USER_INFO = 'SET_USER_INFO'

export const CLEAR_USER_INFO = 'CLEAR_USER_INFO'

export const CLEAR_KAIDIAN_NOTE = 'CLEAR_KAIDIAN_NOTE'

export const NOTE_KAIDIAN = 'NOTE_KAIDIAN'

export const SET_SHOP_LIST = 'SET_SHOP_LIST'

export const CLEAR_SHOP_LIST = 'CLEAR_SHOP_LIST'

export const SET_SHOP_DETAIL = 'SET_SHOP_DETAIL'

export const SET_SHOP_DISHS = 'SET_SHOP_DISHS'

export const CLEAR_CART_LIST = 'CLEAR_CART_LIST'

export const SET_CART_LIST = 'SET_CART_LIST'

export const SET_SHOPTYPE = 'SET_SHOPTYPE'

export const SET_RE_LOGIN = 'SET_RE_LOGIN'
