
export const SET_SUGGESTIONS_LIST = 'SET_SUGGESTIONS_LIST'

export const SET_COORDINATE = 'SET_COORDINATE'

export const SAVE_EXACT_ADDRESS = 'SAVE_EXACT_ADDRESS'

export const CLEAR_SUGGESTIONS_LIST = 'CLEAR_SUGGESTIONS_LIST'

export const SET_INEXACT_CITY = 'SET_INEXACT_CITY'
